package com.trading.orderreliability.order.domain.state;

public enum OrderTransitionTrigger {
    BROKER_ORDER_ACKNOWLEDGED,
    BROKER_ORDER_REJECTED,
    BROKER_ORDER_PARTIALLY_FILLED,
    BROKER_ORDER_FILLED,
    CANCEL_REQUESTED,
    BROKER_CANCEL_ACKNOWLEDGED,
    BROKER_CANCEL_REJECTED,
    BROKER_ORDER_EXPIRED,
    SUBMIT_OUTCOME_TIMED_OUT,
    CANCEL_OUTCOME_TIMED_OUT,
    RECONCILIATION_SNAPSHOT_APPLIED
}
