CREATE TABLE trade_order (
    id BINARY(16) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    market VARCHAR(16) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_type VARCHAR(16) NOT NULL,
    tif VARCHAR(8) NOT NULL,
    order_qty BIGINT NOT NULL,
    limit_price DECIMAL(19,4) NOT NULL,
    status VARCHAR(32) NOT NULL,
    reconciliation_status VARCHAR(32) NOT NULL,
    cum_qty BIGINT NOT NULL,
    leaves_qty BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    terminal_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    INDEX idx_trade_order_account_created_at (account_id, created_at),
    INDEX idx_trade_order_status_updated_at (status, updated_at),
    INDEX idx_trade_order_reconciliation_updated_at (reconciliation_status, updated_at)
);

CREATE TABLE order_instruction (
    id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    instruction_type VARCHAR(32) NOT NULL,
    client_instruction_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL,
    request_payload_json JSON NOT NULL,
    request_payload_hash CHAR(64) NOT NULL,
    result_code VARCHAR(64) NULL,
    result_message VARCHAR(512) NULL,
    trace_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    resolved_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_order_instruction_idempotency UNIQUE (account_id, instruction_type, client_instruction_id),
    INDEX idx_order_instruction_order_type_status (order_id, instruction_type, status),
    INDEX idx_order_instruction_status_updated_at (status, updated_at),
    INDEX idx_order_instruction_trace_id (trace_id)
);

CREATE TABLE order_event (
    id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_version INT NOT NULL,
    source VARCHAR(64) NOT NULL,
    source_message_id BINARY(16) NULL,
    dedup_key VARCHAR(192) NULL,
    payload_hash CHAR(64) NULL,
    trace_id VARCHAR(64) NULL,
    payload_json JSON NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    recorded_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_order_event_dedup_key UNIQUE (dedup_key),
    INDEX idx_order_event_order_recorded_at (order_id, recorded_at),
    INDEX idx_order_event_type_recorded_at (event_type, recorded_at),
    INDEX idx_order_event_trace_id (trace_id),
    INDEX idx_order_event_source_message_id (source_message_id)
);
